### signup
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "dd@ll.com",
  "password": "ddll",
  "career": "webdeveloper"
}


### findOne by ID
GET http://localhost:3000/auth/1


### findMany by career
GET http://localhost:3000/auth?career=plumber


### update user
PATCH http://localhost:3000/auth/3
Content-Type: application/json

{
  "career": "dentist"
}


### delete user
DELETE http://localhost:3000/auth/2 
