### signup
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "test",
  "career": "Car Mechanic"
}


### findOne by ID
GET http://localhost:3000/auth/4


### findMany by career
GET http://localhost:3000/auth?career=Car Mechanic


### update user
PATCH http://localhost:3000/auth/3
Content-Type: application/json

{
  "career": "dentist"
}


### delete user
DELETE http://localhost:3000/auth/2 
